AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - bin/**/*

require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 215

Style/Documentation:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Metrics/AbcSize:
  Max: 45

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/ParameterLists:
  MaxOptionalParameters: 4

Metrics/MethodLength:
  Max: 32

Metrics/ModuleLength:
  Max: 220

Metrics/PerceivedComplexity:
  Max: 15

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Max: 60
