---
name: edge
on: pull_request
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.7
            gemfile: 'gemfiles/rails_edge.gemfile'
          - ruby: 2.7
            gemfile: 'gemfiles/rack_edge.gemfile'
          - ruby: 2.7
            gemfile: 'gemfiles/rack3.gemfile'
          - ruby: "ruby-head"
          - ruby: "truffleruby-head"
          - ruby: "jruby-head"
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        rubygems: latest

    - name: Run tests
      run: bundle exec rake spec

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.ruby }}-${{ matrix.gemfile }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
