---
name: test
on: [push, pull_request]
jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.6', '2.7', '3.0', '3.1', '3.2']
        gemfile: [multi_json, multi_xml, rack_1_0, rack_2_0, rack_2_2, rails_5_2, rails_6_0, rails_6_1, rails_7_0]
        exclude:
          - ruby: '2.6'
            gemfile: rails_7_0

    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        rubygems: latest

    - name: Run tests
      run: bundle exec rake spec

    - name: Run tests (spec/integration/eager_load)
      # with rack-test < 2, rack_2_2.gemfile is equals to Gemfile
      if: ${{ matrix.gemfile == 'gemfiles/rack_2_2.gemfile' }}
      run: bundle exec rspec spec/integration/eager_load

    - name: Run tests (spec/integration/multi_json)
      if: ${{ matrix.gemfile == 'gemfiles/multi_json.gemfile' }}
      run: bundle exec rspec spec/integration/multi_json

    - name: Run tests (spec/integration/multi_xml)
      if: ${{ matrix.gemfile == 'gemfiles/multi_xml.gemfile' }}
      run: bundle exec rspec spec/integration/multi_xml

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.ruby }}-${{ matrix.gemfile }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true